package engine.algorithm;

import java.util.HashMap;
import java.util.Observable;
import java.util.Observer;

/**
 * Stores into the database the values generated by RunGE execution.
 *
 */
public class RunGeObserver implements Observer {
    @Override
    public void update(Observable o, Object arg) {
        HashMap<String, Object> dataMap = (HashMap<String, Object>) arg;

        // Tomando datos del diccionario:
        // Generación actual
        int currGen = Integer.valueOf(dataMap.get("CurrentGeneration").toString());
        // Porcentaje de ejecución
        int currPercent = Math.round((currGen * 100) / Integer.valueOf(dataMap.get("MaxGenerations").toString()));

        // Uno de los dos es null.

        // Valor actual de mejor individuo
        double currBest = Double.valueOf(dataMap.get("BestObjective").toString());

        // Multi-objetivo muestra el frente de objetivos (no será necesario, pero no borrar)
        double objs[][] = (double [][]) dataMap.get("Objectives");

        /*
        if (dataMap.get("BestObjective") != null) {
            currBest = Double.valueOf(dataMap.get("BestObjective").toString());

        } else if (dataMap.get("Objectives") != null) {
            double objs[][] = (double [][]) dataMap.get("Objectives");
        }
         */


        // Habría que escribir estos datos en la BD.

    }
}
